Leaderboard
virtualcommons/port-of-mars pull request #855
Opened 2023-03-28 21:36 UTC by sgfost

Adds global high scores and personal game history pages

resolves #852 
resolves #851

2023-03-28 21:39 UTC, sgfost commented
Looking this over again, it seems like commit history got a bit mangled (probably by github desktop) with a merge creating duplicate commits, easily fixable but ought to be done before merging this

2023-04-06 00:53 UTC, Tkawamura02 commented
UPDATED TASKS FOR THIS ISSUE
- [ ] 1. fix any corner cases / bugs in the query logic that are causing the current leaderboard issues with the null points
- [ ] 2. Ensure that the only games ending in success count in the points total for a given player
- [ ] 3. Embed a short summary leaderboard view in the landing page as a contrasting section (after Gameplay?). This would only include the top 10 players and could be parameterizable Prop for the component
- [ ] 4. Minor styling improvements as needed

2023-04-06 02:12 UTC, saachibm commented
> UPDATED TASKS FOR THIS ISSUE
> 
> * [ ]  1. fix any corner cases / bugs in the query logic that are causing the current leaderboard issues with the null points
> * [ ]  2. Ensure that the only games ending in success count in the points total for a given player
> * [ ]  3. Embed a short summary leaderboard view in the landing page as a contrasting section (after Gameplay?). This would only include the top 10 players and could be parameterizable Prop for the component
> * [ ]  4. Minor styling improvements as needed

Tiffany and I worked on task 2 and are continuing to figure out how to fix null points/corner cases (4/5/23)

2023-04-08 00:28 UTC, sgfost commented
Just need to clean up the player stats/past games page for this to be ready to merge

2023-04-21 05:55 UTC, alee requested changes
Overall everything looks great but see the comments inline. Also I think there may be a bug in the player stats code (see screenshot) - the code in LeaderboardService looks OK though so I'm not exactly sure where it may be arising from.

![image](https://user-images.githubusercontent.com/22534/233550593-d4670b15-811b-4aab-8053-9f3eb2e2972d.png)

2023-04-21 22:41 UTC, sgfost commented on server/src/routes/leaderboard.ts
> +leaderboardRouter.get("/", async (req, res, next) => {
Ended up resolving this alongside the other renaming, `stats` is now the base url/service name/category for directory naming purposes

2023-04-21 22:56 UTC, sgfost commented on client/src/views/Home.vue
> +              <b-link :to="playerStats">personal stats page</b-link> and visit the
-> #857

2023-04-21 22:56 UTC, sgfost commented on client/src/views/PlayerStats.vue
> +          <PlayerStat v-for="item in playerStatItems" :key="item.time" :playerStatItem="item">
-> #858

2023-04-21 22:58 UTC, sgfost commented
Should be good to go @alee, anything not addressed in the last couple of commits are in new issues

2023-04-22 07:28 UTC, alee approved these changes
LGTM thanks all!

2023-04-22 07:29 UTC, merged

2023-05-03 18:30 UTC, alee commented
@all-contributors
please add @sgfost for mentoring, code, doc, and design
please add @Tkawamura02 for code, doc, and design
please add @saachibm for code, doc, and design